# Generated by Django 3.2 on 2022-04-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaryapp', '0002_auto_20220402_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='example',
        ),
    ]
